twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'extensions/form/custom_types.html.twig'
    globals:
        appServiceName: '%env(APP_SERVICE_NAME)%'
        appHost: '%env(APP_HOST)%'
        appMailAdmin: '%env(MAIL_ADMIN)%'
